Article indexes as u64 instead of u32
sgg/brokaw pull request #25
Opened 2020-09-11 08:36 UTC by mellon85

The RFC specifies that article counts fit in a signed int, but the limit
has been surpassed in some newsgroups, and servers are returning numbers
that would fit in a u64.

2020-09-13 19:12 UTC, sgg requested changes
Thanks for the PR!

2020-09-13 19:12 UTC, sgg commented on examples/xfeature_compression.rs
> +use crate::types::ArticleNumber;
```suggestion
use brokaw::types::ArticleNumber;
```

2020-09-14 05:28 UTC, mellon85 commented on examples/xfeature_compression.rs
> +use crate::types::ArticleNumber;
done!

2020-09-14 15:40 UTC, sgg approved these changes

2020-09-14 15:40 UTC, merged